// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: auditlog/v1/fingerprint.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Signature_Method int32

const (
	Signature_METHOD_UNSPECIFIED Signature_Method = 0
	// sign sha256 of content's by RSA SignPKCS1v15
	Signature_METHOD_RSA_PKCS1V15_SHA256 Signature_Method = 1
)

// Enum value maps for Signature_Method.
var (
	Signature_Method_name = map[int32]string{
		0: "METHOD_UNSPECIFIED",
		1: "METHOD_RSA_PKCS1V15_SHA256",
	}
	Signature_Method_value = map[string]int32{
		"METHOD_UNSPECIFIED":         0,
		"METHOD_RSA_PKCS1V15_SHA256": 1,
	}
)

func (x Signature_Method) Enum() *Signature_Method {
	p := new(Signature_Method)
	*p = x
	return p
}

func (x Signature_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signature_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_auditlog_v1_fingerprint_proto_enumTypes[0].Descriptor()
}

func (Signature_Method) Type() protoreflect.EnumType {
	return &file_auditlog_v1_fingerprint_proto_enumTypes[0]
}

func (x Signature_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Signature_Method.Descriptor instead.
func (Signature_Method) EnumDescriptor() ([]byte, []int) {
	return file_auditlog_v1_fingerprint_proto_rawDescGZIP(), []int{0, 0}
}

// general signature field
type Signature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method Signature_Method `protobuf:"varint,1,opt,name=method,proto3,enum=auditlog.v1.Signature_Method" json:"method,omitempty"`
	// signature of content
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// certificate chain of signature, in PEM format
	CertsChainPem string `protobuf:"bytes,3,opt,name=certs_chain_pem,json=certsChainPem,proto3" json:"certs_chain_pem,omitempty"`
}

func (x *Signature) Reset() {
	*x = Signature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auditlog_v1_fingerprint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_auditlog_v1_fingerprint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_auditlog_v1_fingerprint_proto_rawDescGZIP(), []int{0}
}

func (x *Signature) GetMethod() Signature_Method {
	if x != nil {
		return x.Method
	}
	return Signature_METHOD_UNSPECIFIED
}

func (x *Signature) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Signature) GetCertsChainPem() string {
	if x != nil {
		return x.CertsChainPem
	}
	return ""
}

type VersionFingerprint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *VersionFingerprint) Reset() {
	*x = VersionFingerprint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auditlog_v1_fingerprint_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionFingerprint) ProtoMessage() {}

func (x *VersionFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_auditlog_v1_fingerprint_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionFingerprint.ProtoReflect.Descriptor instead.
func (*VersionFingerprint) Descriptor() ([]byte, []int) {
	return file_auditlog_v1_fingerprint_proto_rawDescGZIP(), []int{1}
}

func (x *VersionFingerprint) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VersionFingerprint) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// fingerprint of cluster
type ClusterFingerprint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version   uint32     `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Signature *Signature `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// contains all children objects' fingerprint
	Fingerprints []*VersionFingerprint `protobuf:"bytes,3,rep,name=fingerprints,proto3" json:"fingerprints,omitempty"`
}

func (x *ClusterFingerprint) Reset() {
	*x = ClusterFingerprint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auditlog_v1_fingerprint_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterFingerprint) ProtoMessage() {}

func (x *ClusterFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_auditlog_v1_fingerprint_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterFingerprint.ProtoReflect.Descriptor instead.
func (*ClusterFingerprint) Descriptor() ([]byte, []int) {
	return file_auditlog_v1_fingerprint_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterFingerprint) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClusterFingerprint) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ClusterFingerprint) GetFingerprints() []*VersionFingerprint {
	if x != nil {
		return x.Fingerprints
	}
	return nil
}

var File_auditlog_v1_fingerprint_proto protoreflect.FileDescriptor

var file_auditlog_v1_fingerprint_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x75, 0x64, 0x69, 0x74, 0x6c, 0x6f, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x69,
	0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x61, 0x75, 0x64, 0x69, 0x74, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x22, 0xca, 0x01, 0x0a,
	0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x61, 0x75, 0x64,
	0x69, 0x74, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x26, 0x0a, 0x0f, 0x63, 0x65, 0x72, 0x74, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x70,
	0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x65, 0x72, 0x74, 0x73, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x50, 0x65, 0x6d, 0x22, 0x40, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x12, 0x16, 0x0a, 0x12, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x4d, 0x45, 0x54,
	0x48, 0x4f, 0x44, 0x5f, 0x52, 0x53, 0x41, 0x5f, 0x50, 0x4b, 0x43, 0x53, 0x31, 0x56, 0x31, 0x35,
	0x5f, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x10, 0x01, 0x22, 0x40, 0x0a, 0x12, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xa9, 0x01, 0x0a, 0x12,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69,
	0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x74, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x43, 0x0a, 0x0c, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x74,
	0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x69,
	0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x0c, 0x66, 0x69, 0x6e, 0x67, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x73, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x61, 0x69, 0x73, 0x6b, 0x79, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x74, 0x6c, 0x6f, 0x67, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_auditlog_v1_fingerprint_proto_rawDescOnce sync.Once
	file_auditlog_v1_fingerprint_proto_rawDescData = file_auditlog_v1_fingerprint_proto_rawDesc
)

func file_auditlog_v1_fingerprint_proto_rawDescGZIP() []byte {
	file_auditlog_v1_fingerprint_proto_rawDescOnce.Do(func() {
		file_auditlog_v1_fingerprint_proto_rawDescData = protoimpl.X.CompressGZIP(file_auditlog_v1_fingerprint_proto_rawDescData)
	})
	return file_auditlog_v1_fingerprint_proto_rawDescData
}

var file_auditlog_v1_fingerprint_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auditlog_v1_fingerprint_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_auditlog_v1_fingerprint_proto_goTypes = []interface{}{
	(Signature_Method)(0),      // 0: auditlog.v1.Signature.Method
	(*Signature)(nil),          // 1: auditlog.v1.Signature
	(*VersionFingerprint)(nil), // 2: auditlog.v1.VersionFingerprint
	(*ClusterFingerprint)(nil), // 3: auditlog.v1.ClusterFingerprint
}
var file_auditlog_v1_fingerprint_proto_depIdxs = []int32{
	0, // 0: auditlog.v1.Signature.method:type_name -> auditlog.v1.Signature.Method
	1, // 1: auditlog.v1.ClusterFingerprint.signature:type_name -> auditlog.v1.Signature
	2, // 2: auditlog.v1.ClusterFingerprint.fingerprints:type_name -> auditlog.v1.VersionFingerprint
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_auditlog_v1_fingerprint_proto_init() }
func file_auditlog_v1_fingerprint_proto_init() {
	if File_auditlog_v1_fingerprint_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auditlog_v1_fingerprint_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auditlog_v1_fingerprint_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionFingerprint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auditlog_v1_fingerprint_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterFingerprint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auditlog_v1_fingerprint_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auditlog_v1_fingerprint_proto_goTypes,
		DependencyIndexes: file_auditlog_v1_fingerprint_proto_depIdxs,
		EnumInfos:         file_auditlog_v1_fingerprint_proto_enumTypes,
		MessageInfos:      file_auditlog_v1_fingerprint_proto_msgTypes,
	}.Build()
	File_auditlog_v1_fingerprint_proto = out.File
	file_auditlog_v1_fingerprint_proto_rawDesc = nil
	file_auditlog_v1_fingerprint_proto_goTypes = nil
	file_auditlog_v1_fingerprint_proto_depIdxs = nil
}
